# Generated by Django 4.0 on 2022-02-14 21:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AGSTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task', models.JSONField(default=dict)),
                ('files', models.TextField(blank=True)),
                ('result', models.TextField(blank=True)),
                ('createdDT', models.DateTimeField(auto_now_add=True)),
                ('completedDT', models.DateTimeField(blank=True, null=True)),
                ('progress', models.TextField(blank=True)),
                ('owner', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['createdDT'],
            },
        ),
        migrations.CreateModel(
            name='AGSDocuments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.FileField(blank=True, null=True, upload_to='ags/documents/%Y/%m/%d')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskfiles', to='AGSTask.agstask')),
            ],
        ),
    ]
